version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: cardapio-db
    environment:
      POSTGRES_DB: delivery_app
      POSTGRES_USER: cardapio_user
      POSTGRES_PASSWORD: cardapio_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # pgAdmin (opcional - interface gráfica para o banco)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cardapio-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cardapio.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: